apiVersion: batch/v1
kind: Job
metadata:
   name: pocket-datanode-dram-job
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: pocket-datanode-dram
    spec:
      hostNetwork: true
      restartPolicy: "OnFailure"
      privileged: true
      containers:
      - name: pocket-datanode-dram
        #image: anakli/pocket-datanode-dram:shell
        image: anakli/pocket-datanode-dram:auto
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
        volumeMounts:
        - mountPath: /dev
          name: dev
        ports:
        - containerPort: 50030
      volumes:
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      nodeSelector: 
        pocketnodetype: "dram"

